sudo: false
cache:
  directories:
    - node_modules
language: node_js
node_js:
  - 6.9.2
before_install:
  # for debugging travis, just in case
  - 'env'
  # preprod auto-deploy key for "real" pushes (not for pull requests). http://docs.travis-ci.com/user/encrypting-files/
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && openssl aes-256-cbc -K $encrypted_9c67d478eacb_key -iv $encrypted_9c67d478eacb_iv -in devkeys/swarmsim-preprod.pem.enc -out devkeys/swarmsim-preprod.pem -d || true'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && chmod 600 devkeys/swarmsim-preprod.pem || true'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && eval `ssh-agent` || true'
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && ssh-add devkeys/swarmsim-preprod.pem || true'
  # push a page to preprod that says tests are running
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && .travis/deploy_releasewatch_preprod.sh || true'
  # done with preprod setup
  - 'gem install compass'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" -a "${TRAVIS_BRANCH}" = "master" ] && grunt deploy-preprod --user.name="Evan Rosson (via travis-ci.org robots)" --user.email=`echo "genivf-pv@fjnezfvz.pbz" | tr "[A-Za-z]" "[N-ZA-Mn-za-m]"` || true'
